/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wingjay_jayandroid_fastblur_FastBlurJni */

#ifndef _Included_com_wingjay_jayandroid_fastblur_FastBlurJni
#define _Included_com_wingjay_jayandroid_fastblur_FastBlurJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wingjay_jayandroid_fastblur_FastBlurJni
 * Method:    blurIntArray
 * Signature: ([IIII)V
 */
JNIEXPORT void JNICALL Java_com_wingjay_jayandroid_fastblur_FastBlurJni_blurIntArray
        (JNIEnv *, jclass, jintArray, jint, jint, jint);

/*
 * Class:     com_wingjay_jayandroid_fastblur_FastBlurJni
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wingjay_jayandroid_fastblur_FastBlurJni_test__
        (JNIEnv *, jclass);

/*
 * Class:     com_wingjay_jayandroid_fastblur_FastBlurJni
 * Method:    test
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wingjay_jayandroid_fastblur_FastBlurJni_test__I
        (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
